### PR TITLE
Feat/init setup

### PR DESCRIPTION
**Pull request by vaccinatedProgrammer**
## Description

This PR is the next step of previous PR [Feat/minimal setup](https://github.com/KoodooHQ/loan-origination-aggregate-case-data/pull/1/files).

This PR contains the basic initial setup required to gather the aggregated case data from different sources / collections.

### Summary

This PR focuses on:

- Creating graphql endpoint - `findCaseData`
- Setting up graphql `typeDefs`
- Setting up mongo schemas

### Commitment to review

  - Reviewing changes takes about 15 minutes.
  - Reviewing 21 files.

### Review instructions

As this PR only contain basic initial setup towards finding aggregated case data, The review instructions are kept basic.

- Checkout this branch: `feat/init-setup`
- Run `npm ci`
- Just to get essence, I have mocked the response

<details>
 <summary>Query</summary>

```
 query FindCaseData($caseId: String!) {
  findCaseData(caseId: $caseId) {
    application {
    stage
    }
    quotation {
      evaluation {
        quotationReference
      }
    }
    decision {
      overall
    }
  }
}
```
</details>

<details>
 <summary>Mock Response</summary>

```
 {
  "data": {
    "findCaseData": {
      "application": {
        "stage": "selfDeclared"
      },
      "quotation": {
        "evaluation": {
          "quotationReference": "Q0000000000"
        }
      },
      "decision": {
        "overall": "PASSED"
      }
    }
  }
}
```
</details>

### Acceptance criteria

  - [ ] Appropriate Graphql `typeDefs'
  - [ ] Appropriate mongo schemas
  - [ ] Rough request / response 
  - [ ] LGTM :+1: 

### References

- [Previous PR](https://github.com/KoodooHQ/loan-origination-aggregate-case-data/pull/1)
- [Feature Brief](https://k4o.atlassian.net/wiki/spaces/~219746316/pages/887783425/Feature+Brief+Mortgage+applicant+case+view+query+prototype)

### CODE REVIEW

**Comment by FrescoDev** [comment]
💯  Thanks for getting started on this @vaccinatedProgrammer. One general question, what have you got in mind for the mongoose schemas? Just looking at this looks like the case object is returned from graphQL queries - so why the mongo assets?

**Comment by vaccinatedProgrammer** [comment]
> 💯 Thanks for getting started on this @vaccinatedProgrammer. One general question, what have you got in mind for the mongoose schemas? Just looking at this looks like the case object is returned from graphQL queries - so why the mongo assets?

The idea behind adding schemas, to query the collections directly to get the data, unless we are planing to call respective services directly through graphql.

**Comment by FrescoDev** [comment]
> > 💯 Thanks for getting started on this @vaccinatedProgrammer. One general question, what have you got in mind for the mongoose schemas? Just looking at this looks like the case object is returned from graphQL queries - so why the mongo assets?
> 
> The idea behind adding schemas, to query the collections directly to get the data, unless we are planing to call respective services directly through graphql.

🤔 Ah ok, querying the collections directly would work I think but then I'm confused as to the role of GraphQL?

Couldn't you just have a .js file that does something like:

1. connect to dbs
2. query for the data
3. handle responses from queries
4. transform into case shape
5. return as json to the console

**Comment by vaccinatedProgrammer** [comment]
> > > 💯 Thanks for getting started on this @vaccinatedProgrammer. One general question, what have you got in mind for the mongoose schemas? Just looking at this looks like the case object is returned from graphQL queries - so why the mongo assets?
> > 
> > 
> > The idea behind adding schemas, to query the collections directly to get the data, unless we are planing to call respective services directly through graphql.
> 
> 🤔 Ah ok, querying the collections directly would work I think but then I'm confused as to the role of GraphQL?
> 
> Couldn't you just have a .js file that does something like:
> 
> 1. connect to dbs
> 2. query for the data
> 3. handle responses from queries
> 4. transform into case shape
> 5. return as json to the console

Ohh Yes, Initially I thought to call external services using graphql but then realised some of the services still doesn't have find queries in them, So later on decide to querying the collections directly. 
And yes the plan is to have .js file which would have the mentioned logical steps .

**Pull request closed without merging**
