### PR TITLE
Feat/minimal setup

### PR DESCRIPTION
**Pull request by vaccinatedProgrammer**
## Description

🗒️  This repository has been created to understand whether Mortgage application data structure for a full case is in right shape ?!
Refer - [Feature Brief: Mortgage applicant case view query prototype](https://k4o.atlassian.net/wiki/spaces/~219746316/pages/887783425/Feature+Brief+Mortgage+applicant+case+view+query+prototype)

⭐ As this repository is initialise with one of Koodoo standardise template, in order to keep minimal setup for the repository, removing un-necessary files / folders /code.

### Summary

🗑️ Removed,

- Routing related code / files
- GraphQl related extra files
- Middlerwares
- Some of utility files
- Mocks related files
- Files related to external communication 

### Commitment to review

  - Reviewing changes takes about 10 minutes.
  - Reviewing 20 files.

### Acceptance criteria

  - [ ] Have minimal setup
  - [ ] LGTM :+1: 

### References

[Feature Brief ](https://k4o.atlassian.net/wiki/spaces/~219746316/pages/887783425/Feature+Brief+Mortgage+applicant+case+view+query+prototype)

### CODE REVIEW

**Comment by FrescoDev** [comment]
@vaccinatedProgrammer I think it was the right idea to use the template for this in order to keep with conventions and so will give you credit for this as this is good to do as an engineer BUT given this is a internally facing prototype solution, perhaps it would be cleaner and easier to actually start from scratch?

I think you could like do a good solution with just 3-4 files...

main.js
package.json (with only 6-7 dependencies) 
/some-utils

is actually what I had in mind here. 

The template is meant for services whereas this is just a node.js process that needs to be executable from a machine.

**Comment by vaccinatedProgrammer** [comment]
> @vaccinatedProgrammer I think it was the right idea to use the template for this in order to keep with conventions and so will give you credit for this as this is good to do as an engineer BUT given this is a internally facing prototype solution, perhaps it would be cleaner and easier to actually start from scratch?
> 
> I think you could like do a good solution with just 3-4 files...
> 
> main.js package.json (with only 6-7 dependencies) /some-utils
> 
> is actually what I had in mind here.
> 
> The template is meant for services whereas this is just a node.js process that needs to be executable from a machine.

Yes, Keeping minimal setup in mind I could have start from scratch but then my thought process was we might also require additional files / setup following process:

- Few **deployment** files would also be needed (unless we are not planing to deploy it).
- ApolloServer minimal setup required, as we might go with graphql
- For **Error handling and logging** we need few utils, for example
   -  For logging `bunyan` has its tiny setup, 
- Plus, number of files would increase as we also has to **define type definitions** for each required `types` (ex- `application`, `decision`, `quotation`)
- Few more files for **defining schema's** for all required collections.

So keeping all above points in mind I thought to go ahead with the template and then cleaning it by removing un-necessary files/folders/code.

But as you mentioned this would be just a node js executable process, But still I am not sure how we are going to avoid logging, mongo schema's, graphql typeDefs. and deployment files (unless we are not planing to deploy it).

Note - 
following are the files / folders that can get removed if we are not considering deployment
`.github`, `helm`, `dockerFile`, `docker-compose.yml`, `makefile`

**Comment by FrescoDev** [comment]
> > @vaccinatedProgrammer I think it was the right idea to use the template for this in order to keep with conventions and so will give you credit for this as this is good to do as an engineer BUT given this is a internally facing prototype solution, perhaps it would be cleaner and easier to actually start from scratch?
> > I think you could like do a good solution with just 3-4 files...
> > main.js package.json (with only 6-7 dependencies) /some-utils
> > is actually what I had in mind here.
> > The template is meant for services whereas this is just a node.js process that needs to be executable from a machine.
> 
> Yes, Keeping minimal setup in mind I could have start from scratch but then my thought process was we might also require additional files / setup following process:
> 
> * Few **deployment** files would also be needed (unless we are not planing to deploy it).
> * ApolloServer minimal setup required, as we might go with graphql
> * For **Error handling and logging** we need few utils, for example
>   
>   * For logging `bunyan` has its tiny setup,
> * Plus, number of files would increase as we also has to **define type definitions** for each required `types` (ex- `application`, `decision`, `quotation`)
> * Few more files for **defining schema's** for all required collections.
> 
> So keeping all above points in mind I thought to go ahead with the template and then cleaning it by removing un-necessary files/folders/code.
> 
> But as you mentioned this would be just a node js executable process, But still I am not sure how we are going to avoid logging, mongo schema's, graphql typeDefs. and deployment files (unless we are not planing to deploy it).
> 
> Note - following are the files / folders that can get removed if we are not considering deployment `.github`, `helm`, `dockerFile`, `docker-compose.yml`, `makefile`

Gotcha thanks for explanation.

I think that broadly makes sense although I think this part is still something that could be improved -> 1.) Which of the dependencies in your package.json do you actually need? Can any be removed?

it would be good if we could have this not deployed initially and just have a functional node process (and even if we want to - it's easy to manually + the current deployment assets in the repo are not restricted to dev/test

**Comment by vaccinatedProgrammer** [comment]
> Gotcha thanks for explanation.
> 
> I think that broadly makes sense although I think this part is still something that could be improved -> 1.) Which of the dependencies in your package.json do you actually need? Can any be removed?
> 
> it would be good if we could have this not deployed initially and just have a functional node process (and even if we want to - it's easy to manually + the current deployment assets in the repo are not restricted to dev/test

Got it 👍 , Let me create a new branch which will have all the changes discussed on these related PR's.
And also will add some logic as well so that it would be easier to discuss next steps or changes.

Thanks for the inputs Kojo 👍

**Pull request closed without merging**
